spring:
  main:
    banner-mode: "off"
  
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_SMTP_USERNAME}
    password: ${BREVO_SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

#  cloud:
#    gcp:
#      firestore:
#        project-id: ${VITE_FIREBASE_PROJECT_ID}
#        credentials:
#          location: classpath:example.serviceAccountKey.json
# spring:
  config:
    import: 
      - optional:file:.env